### ISSUE TITLE
[Question] Not using ffprobe?

### ISSUE THREAD

**Issue by FedericoCarboni** [Tenpi/crunchyroll.ts#1]
I am interested in the reason behind the following change https://github.com/Tenpi/crunchyroll.ts/commit/6625576e85bfa966855dc4adb1127d03ca8c6667#diff-915590c37c43298707c38c703c1e224cee04071336874965c8deab848f5899f4L152

I am guessing this was done to avoid vendoring the `ffprobe` binary in [Crunchyroll-Downloader](https://github.com/Tenpi/Crunchyroll-Downloader), decreasing the total size of the app.
To reduce the total size of the FFmpeg binaries you could also use the shared version: essential libraries like `libavformat` and `libavcodec` would be shared between `ffmpeg` and `ffprobe`, instead of being duplicated.

Avoiding `ffprobe` entirely offers a possibility for a minor performance improvement, which is currently unused. Instead of spawning another FFmpeg process, you could parse the logs directly from the download/convert process. This would improve performance because it spawns FFmpeg only once and it sends one request to the download URL (which could also reduce the risk of getting rate-limited, since the Crunchyroll API is used unofficially). The only difference is that it would be precise to one centisecond (`ffprobe` could technically show the duration in µs).
If it is a welcome change I will submit a pull request.

**Comment by Tenpi** [comment]
> I am interested in the reason behind the following change [6625576#diff-915590c37c43298707c38c703c1e224cee04071336874965c8deab848f5899f4L152](https://github.com/Tenpi/crunchyroll.ts/commit/6625576e85bfa966855dc4adb1127d03ca8c6667#diff-915590c37c43298707c38c703c1e224cee04071336874965c8deab848f5899f4L152)

I was having issues with it, you can see it by running [Crunchyroll Downloader](https://github.com/Tenpi/Crunchyroll-Downloader) with `crunchyroll.ts@0.2.8`, the version before that commit. The error message it logs is `{ ffprobePath: undefined }` (it's just the input arguments). It's probably a bug in that app because it works ok directly from this repo, but I just decided to fix it by removing ffprobe altogether. Reducing the size of the app is also a plus (ffprobe is around 70MB).

All contributions/pull requests are welcome. I would actually like it if `duration` and `percent` was available in the FFmpeg progress, it's really useful info to have when you want to make a progress bar. Then I wouldn't have to parse them manually, but if that's not possible your solution is also good enough.

**Comment by FedericoCarboni** [comment]
> I would actually like it if duration and percent was available in the FFmpeg progress

A percentage will never be added to the progress because the duration can be modified, there may be more than one input, and it would generally not be reliable with complex filters. Supporting every use case is not trivial. I will eventually add a parser for FFmpeg's logs. I will, hopefully, get to something stable *enough* in the next weeks, but I am only one person, so it will, unfortunately, take some time to implement.

> Avoiding `ffprobe` entirely offers a possibility for a minor performance improvement

About this, I will (hopefully) submit a PR this week.

**Comment by Tenpi** [comment]
Closing this since it was answered.
